# Thunderbird in a container
#
# sudo docker run --cpus="3" -d \
#             -v /tmp/.X11-unix:/tmp/.X11-unix \
#             -v /home/johnk/:/home/user \
#             -v /etc/localtime:/etc/localtime:ro \
#             -e DISPLAY=unix$DISPLAY \
#             --device /dev/dri frumioj/webex-docked

FROM centos:8
LABEL maintainer "John Kemp <stable.pseudonym@gmail.com>"

RUN yum update -y \
    && yum install -y wget

RUN wget https://binaries.webex.com/WebexDesktop-CentOS-Official-Package/Webex.rpm

RUN yum install -y ./Webex.rpm

ENV HOME /home/user
RUN useradd --create-home --home-dir $HOME user \
	&& chown -R user:user $HOME

COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

WORKDIR $HOME

CMD [ "start.sh" ]